//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinalWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle
    {
        public int id_detalle { get; set; }
        public Nullable<int> producto { get; set; }
        public Nullable<int> pedido { get; set; }
    
        public virtual pedido pedido1 { get; set; }
        public virtual producto producto1 { get; set; }
    }
}
